backend:
  name: github
  repo: jekyll-one-org/j1-template
  branch: decap-cms

# Enables a local proxy backend for development with `npx decap-server`.
local_backend: true

site_url: http://localhost:40000
logo_url: /assets/image/icon/mk/mk-512x512.png

media_folder: assets/uploads
public_folder: /assets/uploads

publish_mode: editorial_workflow
search: true

collections:
  - name: about_pages
    label: MK Site Pages
    label_singular: MK Site Page
    folder: pages/public/about
    create: true
    extension: adoc
    format: yaml-frontmatter
    slug: "{{slug}}"
    preview_path: "pages/public/about/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Tagline, name: tagline, widget: string, required: false }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD", time_format: false }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Keywords, name: keywords, widget: text, required: false }
      - { label: Categories, name: categories, widget: list, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - label: Permalink
        name: permalink
        widget: string
        hint: "Use the J1 path style, e.g. /pages/public/about/my-page/"
      - { label: Comments Enabled, name: comments, widget: boolean, required: false, default: false }
      - { label: Regenerate, name: regenerate, widget: boolean, required: false, default: false }
      - { label: Body, name: body, widget: text }

  - name: portfolio_entries
    label: MK Portfolio
    label_singular: MK Portfolio Entry
    folder: collections/_portfolio
    create: true
    extension: adoc
    format: yaml-frontmatter
    slug: "{{slug}}"
    preview_path: "collections/public/portfolio/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD", time_format: false, required: false }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Body, name: body, widget: text }

  - name: people_entries
    label: MK Team
    label_singular: MK Team Member
    folder: collections/_people
    create: true
    extension: adoc
    format: yaml-frontmatter
    slug: "{{slug}}"
    preview_path: "collections/public/people/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD", time_format: false, required: false }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Body, name: body, widget: text }
