---
title:                                  Trail Map
tagline:                                Interactive
date:                                   2026-06-11
#last_modified:                         2026-06-11

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        Simple documents are used quite often. If the number
                                        of chapters is about or less than three and the document
                                        is small in size. This document type does not use any
                                        (local) Asciidoc include files or attributes.

categories:                             [ Knowledge, Asciidoc ]
tags:                                   [ Skeleton, SimpleDocument ]

robots:
  index:                                false
  follow:                               false

image:
  path:                                 /assets/uploads/lifts123.jpg
  width:                                1920
  height:                               1280

personalization:                        false
comments:                               false
exclude_from_search:                    false
fab_menu_id:                            open_toc
scrollbar:                              false
toc:                                    true
regenerate:                             false
permalink:                              /pages/public/mountain/trail-map/

resources:                              [ lightbox, rouge ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/uploads/lifts123.jpg
          alt:                          Photo by Sigmund on Unsplash
          badge:
            type:                       unsplash
            author:                     Sigmund
            href:                       //unsplash.com/@sigmund
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-fontawesome--home:                 https://fontawesome.com/
:url-fontawesome--icons:                https://fontawesome.com/icons?d=gallery/
:url-fontawesome--get-started:          https://fontawesome.com/get-started/

:url-mdi--home:                         https://materialdesignicons.com/
:url-mdi-icons--cheatsheet:             https://cdn.materialdesignicons.com/3.3.92/

:url-iconify--home:                     https://iconify.design/
:url-iconify--icon-sets:                https://iconify.design/icon-sets/
:url-iconify--medical-icons:            https://iconify.design/icon-sets/medical-icon/
:url-iconify--brand-icons:              https://iconify.design/icon-sets/logos/

:url-roundtrip--mdi-icons:              /pages/public/tour/mdi_icon_font/#material-design-icons
:url-roundtrip--fontawesome-icons:      /pages/public/tour/mdi_icon_font/#fontawesome-icons
:url-roundtrip--iconify-icons:          /pages/public/tour/mdi_icon_font/#iconify-icons
:url-roundtrip--asciidoc-extensions:    /pages/public/tour/asciidoc_extensions/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= Mount Kato Interactive Trail Map

== Your Digital Guide to Navigating the Slopes

[[page.description]]
++++
{% include brochure_n_map_downloads.html %}
{% include custom/templates/mk_trail_map_lite.html %}
++++
=== Key Features:

*Dynamic Trail Information:* Click on any trail button to reveal its difficulty level, length, grooming status, and other essential details.
Real-Time Updates: Stay informed about which lifts and trails are open, so you can make the most of your day on the mountain.

*Customizable Views:* Filter trails by difficulty, terrain type, or other preferences to tailor the map to your interests.
Zoom and Pan: Navigate seamlessly across the entire mountain, zooming in for detailed views or zooming out for a broader perspective.
Mobile-Friendly Design: Access the interactive map on your smartphone or tablet for convenient on-the-go planning.

=== Plan Your Perfect Day:

Whether you're a seasoned pro or a first-time visitor, the Mount Kato Interactive Trail Map is your essential companion for navigating the slopes. Use it to plan your ideal route, discover hidden gems, and make the most of your winter adventure at Mount Kato.

++++ 

{% include downloads_card.html %}

++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------