---
title:                                  Safety
tagline:                                Your Well-Being is Our Top Priority
date:                                   2026-06-11
#last_modified:                         2026-06-11

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        Simple documents are used quite often. If the number
                                        of chapters is about or less than three and the document
                                        is small in size. This document type does not use any
                                        (local) Asciidoc include files or attributes.

categories:                             [ Knowledge, Asciidoc ]
tags:                                   [ Skeleton, SimpleDocument ]

robots:
  index:                                false
  follow:                               false

image:
  path:                                 /assets/uploads/lifts123.jpg
  width:                                1920
  height:                               1280

personalization:                        false
comments:                               false
exclude_from_search:                    false
fab_menu_id:                            open_toc
scrollbar:                              false
toc:                                    true
regenerate:                             false
permalink:                              /pages/public/mountain/safety/

resources:                              [ lightbox, rouge ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/uploads/lifts123.jpg
          alt:                          Photo by Sigmund on Unsplash
          badge:
            type:                       unsplash
            author:                     Sigmund
            href:                       //unsplash.com/@sigmund
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-fontawesome--home:                 https://fontawesome.com/
:url-fontawesome--icons:                https://fontawesome.com/icons?d=gallery/
:url-fontawesome--get-started:          https://fontawesome.com/get-started/

:url-mdi--home:                         https://materialdesignicons.com/
:url-mdi-icons--cheatsheet:             https://cdn.materialdesignicons.com/3.3.92/

:url-iconify--home:                     https://iconify.design/
:url-iconify--icon-sets:                https://iconify.design/icon-sets/
:url-iconify--medical-icons:            https://iconify.design/icon-sets/medical-icon/
:url-iconify--brand-icons:              https://iconify.design/icon-sets/logos/

:url-roundtrip--mdi-icons:              /pages/public/tour/mdi_icon_font/#material-design-icons
:url-roundtrip--fontawesome-icons:      /pages/public/tour/mdi_icon_font/#fontawesome-icons
:url-roundtrip--iconify-icons:          /pages/public/tour/mdi_icon_font/#iconify-icons
:url-roundtrip--asciidoc-extensions:    /pages/public/tour/asciidoc_extensions/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
At Mount Kato, your safety is our top priority. We are committed to providing a fun and enjoyable experience for all guests while maintaining a secure environment on and off the slopes.

++++
{% include lift-safety-modal.html %}
++++

[role="mt-5"]
== Our Commitment to Safety

*Trained Staff:* Our team members undergo rigorous training in safety procedures, first aid, and emergency response to ensure a swift and appropriate response to any situation.

*Regular Inspections:* We conduct thorough inspections of all equipment and facilities to identify and address potential hazards.

*Clear Signage:* Informative signage is strategically placed throughout the resort to remind guests of safety guidelines and potential risks.

*Safety Education:* We offer educational resources and programs to promote responsible behavior on the slopes and awareness of potential hazards.


[role="mt-5"]

*Ski and Ride Within Your Ability:* Choose trails that match your skill level and avoid taking unnecessary risks.

*Use Proper Equipment:* Wear a helmet, ensure your bindings are adjusted correctly, and use appropriate gear for the conditions.

*Respect Others:* Be mindful of other skiers and snowboarders and yield to those downhill.

*Stay Hydrated and Fueled:* Take breaks, drink plenty of water, and eat nutritious snacks to maintain your energy levels.

*Report Hazards:* If you see any unsafe conditions or potential hazards, please report them to a staff member immediately.

Together, we can create a safe and enjoyable experience for everyone at Mount Kato. By following these guidelines and being mindful of others, we can ensure that your visit is filled with fun, excitement, and lasting memories.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
++++
<!-- Button trigger modal -->
<div class="mx-auto p-2" style="width: 200px;">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Downloads
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Mount Kato Brochures & Maps</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <center><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfP7WFHxmVCW9tIBd3Ll3SUurAeud7VLdqYDGtNXsoW2VWJTA/viewform?embedded=true" width="450
          " height="1200" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe></center>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</div>
++++